//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Collections.Generic;
    
    public partial class activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activities()
        {
            this.jury_activities = new HashSet<jury_activities>();
            this.moderator_activities = new HashSet<moderator_activities>();
        }
    
        public int activity_id { get; set; }
        public string activity_name { get; set; }
        public string description { get; set; }
        public int event_id { get; set; }
        public int activity_day { get; set; }
        public System.TimeSpan start_time { get; set; }
        public Nullable<int> duration_minutes { get; set; }
    
        public virtual events events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_activities> jury_activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moderator_activities> moderator_activities { get; set; }
    }
}
