//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_event
    {
        public int id { get; set; }
        public int event_id { get; set; }
        public int city_id { get; set; }
    
        public virtual cities cities { get; set; }
        public virtual events events { get; set; }
    }
}
