//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_registrations
    {
        public int registration_id { get; set; }
        public int event_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime registration_date { get; set; }
        public string status { get; set; }
    
        public virtual events events { get; set; }
        public virtual users users { get; set; }
    }
}
