//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderator_activities
    {
        public int moderator_activity_id { get; set; }
        public int activity_id { get; set; }
        public int moderator_id { get; set; }
    
        public virtual activities activities { get; set; }
        public virtual users users { get; set; }
    }
}
