//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceDBEntities : DbContext
    {
        public ConferenceDBEntities()
            : base("name=ConferenceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<city_event> city_event { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<directions> directions { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<genders> genders { get; set; }
        public virtual DbSet<jury_activities> jury_activities { get; set; }
        public virtual DbSet<moderator_activities> moderator_activities { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
