//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._02._01_Vybornov
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.event_registrations = new HashSet<event_registrations>();
            this.jury_activities = new HashSet<jury_activities>();
            this.moderator_activities = new HashSet<moderator_activities>();
        }
    
        public int user_id { get; set; }
        public string id_number { get; set; }
        public string password_hash { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> country_id { get; set; }
        public string phone { get; set; }
        public string photo_path { get; set; }
        public Nullable<int> gender_id { get; set; }
        public int role_id { get; set; }
        public Nullable<int> direction_id { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual directions directions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_registrations> event_registrations { get; set; }
        public virtual genders genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jury_activities> jury_activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moderator_activities> moderator_activities { get; set; }
        public virtual roles roles { get; set; }
    }
}
